### ISSUE TITLE
Issue with Myo list visualization

### ISSUE THREAD

**Issue by cortinico** [meleap/myo_AndoridEMG#3]
There is an issue with Myo listing. 
When you press on Menu -> Find Myo you can see a list with 5 elements filled with "-"
![screenshot1](http://s2.postimg.org/v23nwiim1/Screenshot_2015_05_12_11_05_16.png)

When you press the button "Scan" on the bottom you can see 5 different Myo entries all with the same name
![screenshot2](http://s21.postimg.org/vzvgtg71j/Screenshot_2015_05_12_11_05_25.png)

**Comment by note-nota** [comment]
Thanks your pull requests !
I was disturbed some other devices, so fix this problem to ignore the "null" device.
